### ISSUE TITLE
Permissions don't match up

### ISSUE THREAD

**Issue by qanwi1970** [OfficeDev/O365-Win-Profile#4]
In the documentation it says to check the "Read Users' Files" permissions, but that permission doesn't show up on the website. The closest option is "Read signed-in user's files." However, when that is checked and I run the application, it fails with an error

AADSTS65001: No permission to access user information is configured for '<client id>' application, or it is expired or revoked.
Trace ID: e1bba6fe-f814-44d1-a46d-e96b32c831a2
Correlation ID: ec8089b4-9dde-408e-a8c8-1af59f36a607
Timestamp: 2015-09-23 18:47:29Z. The remote server returned an error: (400) Bad Request.

**Comment by jamescro** [comment]
Thanks. I am looking into this.

**Comment by jamescro** [comment]
Thanks for your input. We do need to update the permission names, and I am working on that, but the error you're getting seems to be unrelated to this permission. Are you seeing this when you attempt to authenticate? If so, are you seeing a window that prompts you to consent to the permissions that the app needs?

Also, have you registered this app on a tenant other than the one that the signed-in user belongs to?

This can happen sometimes when a user consents to a set of permissions, but then additional permissions are added to the app. In that case, you can fix the problem by manually uninstalling the app and redeploying it.

**Comment by qanwi1970** [comment]
Yes, I get it when trying to authenticate and it doesn't ask for more
permissions.

I'm using the same user all around.

**Comment by jamescro** [comment]
It looks like you're having an app registration issue.

If you have Visual Studio 2015 and Windows 10, could you try this sample? https://github.com/OfficeDev/O365-UWP-Unified-API-Connect
It uses the same endpoint, but with just one permission, so it might help eliminate variables.

**Comment by qanwi1970** [comment]
I haven't gone all the way to trying it yet, but I found something that
might be the problem. My office 365 account is not a business account, as
it says here:

https://msdn.microsoft.com/en-us/office/office365/howto/setup-development-environment#bk_CreateAzureSubscription

I'll keep going on the sample, but just thought I'd ask about that.

I can get

Thanks,
Bill

**Comment by jamescro** [comment]
Yes. This sample does require an O365 for business account. Have you tried signing up for a free developer tenant?

**Comment by jamescro** [comment]
I've updated the readme so that the files permission name matches with what's in the Azure Management Portal. I've also updated the prerequisites section to make it clear that the sample requires and O365 business account. It looks like the permission issue that you're encountering has to do with the type of tenant that you're using. I'll close the issue, but please reopen if you have any issues with the sample running on an O365 business account tenant.
